version: "3.8"

services:
  postgres-db:
    container_name: budget_planner_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: planner
      POSTGRES_DB: budget_db
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
