CREATE TABLE budget_item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    amount      DOUBLE PRECISION                        NOT NULL,
    category    VARCHAR(255),
    date        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_budgetitem PRIMARY KEY (id)
);