#spring.application.name=budget-planner

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_db
    driver-class-name: org.postgresql.Driver
    username: planner
    password: planner
  flyway:
    enabled: true
    locations: classpath:db.migration
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080


